### ISSUE TITLE
Error with python 3.4

### ISSUE THREAD

**Issue by tonyroberts** [fkarb/pythonnet#4]
From @BrisingrAerowing:

Basically Python 3.4 (and 3.3 AFAIK) have larger unicode support and trigger the UCS4 support in PythonNET's setup.py, causing the build to fail as Mono.Posix most likely is not available.

I get around this by editing setup.py to always use UCS2, but this needs to be fixed.

**Comment by brisingraerowing** [comment]
Ah, thanks! I love this project. Keep up the good work!
